<?php
require __DIR__.'/../includes/bootstrap.php'; leader_required(); $leader=staff($pdo); $msg=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $action=(string)($_POST['action']??'');
        if($action==='create'){
            $title=trim((string)($_POST['title']??''));$description=trim((string)($_POST['description']??''));$category=(string)($_POST['category']??'other');$date=(string)($_POST['event_date']??'');$start=trim((string)($_POST['start_time']??''));$end=trim((string)($_POST['end_time']??''));$venue=trim((string)($_POST['venue']??''));$registration=!empty($_POST['registration_required'])?1:0;$deadline=trim((string)($_POST['registration_deadline']??''));$status=(string)($_POST['status']??'published');
            $cats=['worship','bible_study','prayer','youth','outreach','conference','fellowship','special_service','other'];
            if($title===''||mb_strlen($title)>180)throw new RuntimeException('Please provide an event title up to 180 characters.');
            if(!in_array($category,$cats,true)||!in_array($status,['draft','published'],true))throw new RuntimeException('Invalid event category or status.');
            $dt=DateTime::createFromFormat('Y-m-d',$date);if(!$dt||$dt->format('Y-m-d')!==$date||$date<date('Y-m-d'))throw new RuntimeException('Please select a valid future event date.');
            if($start!==''&&!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',$start))throw new RuntimeException('Please enter a valid start time.');
            if($end!==''&&!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',$end))throw new RuntimeException('Please enter a valid end time.');
            if($start!==''&&$end!==''&&$end<=$start)throw new RuntimeException('Event end time must be after the start time.');
            if($registration&&$deadline!==''){$deadline.=':00';$dlt=DateTime::createFromFormat('Y-m-d\TH:i:s',$deadline);if(!$dlt)throw new RuntimeException('Please enter a valid registration deadline.');}else $deadline=null;
            $pdo->beginTransaction();
            $q=$pdo->prepare("INSERT INTO church_events(user_id,title,description,category,event_date,start_time,end_time,venue,registration_required,registration_deadline,status) VALUES(?,?,?,?,?,?,?,?,?,?,?)");
            $q->execute([(int)$leader['id'],$title,$description,$category,$date,$start!==''?$start.':00':null,$end!==''?$end.':00':null,$venue,$registration,$deadline,$status]);$eventId=(int)$pdo->lastInsertId();
            $recipients=0;$emails=0;$pastors=0;
            if($status==='published'){
                $text='A new church event has been published for '.fmt_date($date).($start?' at '.fmt_time($start):'').'. Please open Church Events in your member portal for details.';
                $recipients=notify_all_members($pdo,'New church event: '.$title,$text,'info');
                $pastors=notify_all_pastors($pdo,'New church event created by '.$leader['full_name'],$leader['full_name'].' created the church event “'.$title.'” for '.fmt_date($date).'.','info');
                $pdo->commit();$emails=email_members_about_event($pdo,$eventId,'published');
                email_pastors_about_event($pdo,$eventId,'published');
                log_activity($pdo,null,(int)$leader['id'],'leader_event_published','Published event #'.$eventId.' to '.$recipients.' members; notified '.$pastors.' pastor(s). Emails sent: '.$emails);
                $msg='Event published successfully. Members and the Pastor have been notified.';
            }else{$pdo->commit();log_activity($pdo,null,(int)$leader['id'],'leader_event_draft','Saved leader event draft #'.$eventId);$msg='Event draft saved successfully.';}
        }elseif($action==='cancel'){
            $id=(int)($_POST['id']??0);$q=$pdo->prepare("UPDATE church_events SET status='cancelled' WHERE id=? AND user_id=? AND status='published'");$q->execute([$id,(int)$leader['id']]);
            if(!$q->rowCount())throw new RuntimeException('Event not found or already updated.');
            $q=$pdo->prepare('SELECT title,event_date FROM church_events WHERE id=?');$q->execute([$id]);$ev=$q->fetch();
            if($ev){$text='The church event scheduled for '.fmt_date($ev['event_date']).' has been cancelled. Please check the member portal for updates.';notify_all_members($pdo,'Event cancelled: '.$ev['title'],$text,'warning');email_members_about_event($pdo,$id,'cancelled');notify_all_pastors($pdo,'Church event cancelled',$leader['full_name'].' cancelled “'.$ev['title'].'”.','warning');}
            log_activity($pdo,null,(int)$leader['id'],'leader_event_cancelled','Cancelled event #'.$id);$msg='Event cancelled and notifications sent.';
        }else throw new RuntimeException('Unknown event action.');
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'The event could not be saved.';}
}
$events=$pdo->prepare("SELECT e.*,(SELECT COUNT(*) FROM event_rsvps r WHERE r.event_id=e.id AND r.status='going') going_count,(SELECT COUNT(*) FROM event_rsvps r WHERE r.event_id=e.id AND r.status='maybe') maybe_count FROM church_events e WHERE e.user_id=? ORDER BY e.event_date DESC,e.start_time DESC LIMIT 40");$events->execute([(int)$leader['id']]);$events=$events->fetchAll();
$page_title='Church Events';require __DIR__.'/../includes/header.php';
?>
<div><?php require __DIR__.'/../includes/leader_sidebar.php';?><main class="main"><header class="topbar"><div class="d-flex align-items-center gap-3"><button class="menu-btn" data-sidebar-toggle><i class="bi bi-list"></i></button><div><h1>Church Events</h1><p>Create activities, publish them to members and keep the Pastor informed.</p></div></div><a href="#createEvent" class="btn btn-primary btn-sm"><i class="bi bi-plus-lg me-1"></i>New Event</a></header><div class="content">
<?php if($msg):?><div class="alert alert-success"><i class="bi bi-check-circle me-2"></i><?=e($msg)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><i class="bi bi-exclamation-triangle me-2"></i><?=e($error)?></div><?php endif;?>
<div class="row g-4"><div class="col-xl-5" id="createEvent"><div class="cardx p-4"><h3 class="section-title">Create a church event</h3><p class="text-muted small">Published events notify active members and the Pastor by portal notification and email.</p><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create"><div class="mb-3"><label class="form-label">Event title</label><input name="title" class="form-control" maxlength="180" required></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Category</label><select name="category" class="form-select"><?php foreach(['worship','bible_study','prayer','youth','outreach','conference','fellowship','special_service','other'] as $c):?><option value="<?=$c?>"><?=e(event_category_label($c))?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Date</label><input type="date" name="event_date" class="form-control" min="<?=date('Y-m-d')?>" required></div><div class="col-md-6"><label class="form-label">Start time</label><input type="time" name="start_time" class="form-control"></div><div class="col-md-6"><label class="form-label">End time</label><input type="time" name="end_time" class="form-control"></div></div><div class="mb-3 mt-3"><label class="form-label">Venue / meeting link</label><input name="venue" class="form-control" maxlength="180"></div><div class="mb-3"><label class="form-label">Description</label><textarea name="description" class="form-control" rows="5"></textarea></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="registration_required" id="regRequired"><label class="form-check-label" for="regRequired">Enable member RSVP</label></div><div class="mb-3"><label class="form-label">Registration deadline <span class="text-muted">(optional)</span></label><input type="datetime-local" name="registration_deadline" class="form-control"></div><div class="d-flex gap-2"><button name="status" value="draft" class="btn btn-outline-secondary">Save Draft</button><button name="status" value="published" class="btn btn-primary"><i class="bi bi-send me-1"></i>Publish Event</button></div></form></div></div>
<div class="col-xl-7"><div class="cardx p-4"><h3 class="section-title">Your events</h3><div class="d-grid gap-3"><?php foreach($events as $ev):?><div class="event-card"><div class="d-flex justify-content-between gap-3"><div><h5 class="mb-1"><?=e($ev['title'])?></h5><div class="small text-muted"><?=e(fmt_date($ev['event_date']))?><?= $ev['start_time']?' · '.e(fmt_time($ev['start_time'])):'' ?> · <?=e(event_category_label($ev['category']))?></div><p class="small mt-2 mb-1"><?=e($ev['description']??'')?></p><div class="small text-muted"><?=e($ev['venue']?:'Venue to be announced')?> · RSVP: <?=e((string)$ev['going_count'])?> going, <?=e((string)$ev['maybe_count'])?> maybe</div></div><div class="text-end"><span class="badge text-bg-<?=$ev['status']==='published'?'success':($ev['status']==='draft'?'warning':($ev['status']==='cancelled'?'danger':'secondary'))?>"><?=e(ucfirst($ev['status']))?></span><?php if($ev['status']==='published'&&$ev['event_date']>=date('Y-m-d')):?><form method="post" class="mt-2" onsubmit="return confirm('Cancel this event?');"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="cancel"><input type="hidden" name="id" value="<?=$ev['id']?>"><button class="btn btn-sm btn-outline-danger">Cancel</button></form><?php endif;?></div></div></div><?php endforeach;?><?php if(!$events):?><div class="empty">You have not created any events yet.</div><?php endif;?></div></div></div></div></div></main></div>
<?php require __DIR__.'/../includes/footer.php';?>
