<?php
require __DIR__.'/../includes/bootstrap.php';admin_required();$msg='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{
 $name=trim((string)($_POST['full_name']??''));$username=trim((string)($_POST['username']??''));$email=trim((string)($_POST['email']??''));$phone=trim((string)($_POST['phone']??''));$role=(string)($_POST['role']??'church_leader');$password=(string)($_POST['password']??'');
 if($name===''||$username===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($role,['pastor','church_leader'],true)||strlen($password)<8)throw new RuntimeException('Enter a name, username, valid email, role and a password of at least 8 characters.');
 $q=$pdo->prepare("SELECT id FROM users WHERE username=? OR email=? LIMIT 1");$q->execute([$username,$email]);if($q->fetchColumn())throw new RuntimeException('That username or email is already registered.');
 $q=$pdo->prepare("INSERT INTO users(username,full_name,email,phone,password_hash,role,status) VALUES(?,?,?,?,?,?, 'active')");$q->execute([$username,$name,$email,$phone,password_hash($password,PASSWORD_DEFAULT),$role]);
 $id=(int)$pdo->lastInsertId();if($role==='church_leader'){$pdo->prepare("INSERT INTO leader_profiles(user_id) VALUES(?)")->execute([$id]);}
 log_activity($pdo,null,(int)staff($pdo)['id'],'staff_account_created','Created '.$role.' account for '.$name);
 $msg=ucwords(str_replace('_',' ',$role)).' account created successfully. The person can now use the unified login.';
}catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'The account could not be created.';}}
$page_title='Register Pastor & Leaders';require __DIR__.'/../includes/header.php';?>
<div><?php require __DIR__.'/../includes/admin_sidebar.php';?><main class="main"><header class="topbar"><div class="d-flex align-items-center gap-3"><button class="menu-btn" data-sidebar-toggle><i class="bi bi-list"></i></button><div><h1>Register Pastor & Church Leaders</h1><p>Create staff accounts that automatically receive the correct portal.</p></div></div></header><div class="content"><div class="row justify-content-center"><div class="col-xl-8"><div class="cardx p-4"><?php if($msg):?><div class="alert alert-success"><?=e($msg)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="row g-3"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" name="full_name" required></div><div class="col-md-6"><label class="form-label">Role</label><select class="form-select" name="role"><option value="pastor">Pastor</option><option value="church_leader">Church Leader</option></select></div><div class="col-md-6"><label class="form-label">Username</label><input class="form-control" name="username" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" name="email" type="email" required></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" name="phone"></div><div class="col-md-6"><label class="form-label">Initial password</label><input class="form-control" name="password" type="password" minlength="8" required></div></div><div class="alert alert-info mt-4 small"><i class="bi bi-info-circle me-1"></i>Pastors enter the Pastor Portal. Church Leaders enter the communications-only Leader Portal. Neither role uses email OTP for normal sign-in.</div><button class="btn btn-primary"><i class="bi bi-person-plus me-1"></i>Create account</button></form></div></div></div></div></main></div>
<?php require __DIR__.'/../includes/footer.php';?>