<?php
require __DIR__.'/../includes/bootstrap.php'; admin_required();
$admin=staff($pdo);$msg='';$error='';$temporaryPassword='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $id=(int)($_POST['id']??0);$action=(string)($_POST['action']??'');
        $q=$pdo->prepare("SELECT id,full_name,membership_no,email,status FROM members WHERE id=? LIMIT 1");$q->execute([$id]);$m=$q->fetch();if(!$m)throw new RuntimeException('Member not found.');
        if($action==='toggle_status'){
            $new=$m['status']==='active'?'inactive':'active';$pdo->prepare('UPDATE members SET status=? WHERE id=?')->execute([$new,$id]);log_activity($pdo,null,$admin['id'],'member_status_changed','Changed member '.$m['membership_no'].' status to '.$new.'.');$msg=$m['full_name'].' is now '.ucfirst($new).'.';
        }elseif($action==='reset_password'){
            $temporaryPassword='Fgck'.date('Y').'!'.strtoupper(bin2hex(random_bytes(3)));$pdo->prepare("UPDATE members SET password_hash=?,status='active' WHERE id=?")->execute([password_hash($temporaryPassword,PASSWORD_DEFAULT),$id]);log_activity($pdo,null,$admin['id'],'member_password_reset','Reset password for member '.$m['membership_no'].'.');
            if(filter_var($m['email'],FILTER_VALIDATE_EMAIL)){
                $body='<p>Hello '.e($m['full_name']).',</p><p>Your FGCK Joyland member portal password has been reset by an administrator.</p><p><b>Membership number:</b> '.e($m['membership_no']).'<br><b>Temporary password:</b> <code>'.e($temporaryPassword).'</code></p><p>Please sign in and change your password immediately.</p>';
                $sent=send_system_email($m['email'],$m['full_name'],'Your FGCK Joyland Member Password Was Reset',$body);$msg=$sent?'A temporary password was generated and emailed to the member.':'A temporary password was generated, but the email could not be delivered. Share it securely and check Admin → Email Health.';
            }else{$msg='A temporary password was generated, but the member has no valid email address.';}
        }else throw new RuntimeException('Unknown member action.');
    }catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'The member action could not be completed.';}
}
$search=trim((string)($_GET['q']??''));$status=$_GET['status']??'all';if(!in_array($status,['all','active','inactive'],true))$status='all';
$sql="SELECT id,membership_no,full_name,phone,email,status,last_login_at,created_at FROM members WHERE 1=1";$params=[];if($search!==''){$sql.=" AND (full_name LIKE ? OR membership_no LIKE ? OR phone LIKE ? OR email LIKE ?)";$like='%'.$search.'%';$params=[$like,$like,$like,$like];}if($status!=='all'){$sql.=' AND status=?';$params[]=$status;}$sql.=' ORDER BY full_name LIMIT 500';$q=$pdo->prepare($sql);$q->execute($params);$rows=$q->fetchAll();
$page_title='Member Administration';require __DIR__.'/../includes/header.php';?>
<div><?php require __DIR__.'/../includes/admin_sidebar.php';?><main class="main"><header class="topbar"><div class="d-flex align-items-center gap-3"><button class="menu-btn" data-sidebar-toggle><i class="bi bi-list"></i></button><div><h1>Member Administration</h1><p>Search members, control account access and securely reset member passwords.</p></div></div><span class="live-pill">People administration</span></header><div class="content">
<?php if($msg):?><div class="alert alert-success"><i class="bi bi-check-circle me-2"></i><?=e($msg)?><?php if($temporaryPassword):?><br><strong>Temporary password:</strong> <code><?=e($temporaryPassword)?></code><?php endif;?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><i class="bi bi-exclamation-triangle me-2"></i><?=e($error)?></div><?php endif;?>
<div class="cardx p-4 mb-4"><form class="row g-3 align-items-end" method="get"><div class="col-lg-6"><label class="form-label">Search members</label><input name="q" class="form-control" value="<?=e($search)?>" placeholder="Name, membership number, phone or email"></div><div class="col-lg-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="all" <?=$status==='all'?'selected':''?>>All members</option><option value="active" <?=$status==='active'?'selected':''?>>Active</option><option value="inactive" <?=$status==='inactive'?'selected':''?>>Inactive</option></select></div><div class="col-lg-3 d-flex gap-2"><button class="btn btn-primary flex-grow-1"><i class="bi bi-search me-1"></i>Search</button><a href="/admin/members" class="btn btn-outline-secondary">Reset</a></div></form></div>
<div class="cardx p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h3 class="section-title mb-1">Member accounts</h3><p class="text-muted small mb-0"><?=count($rows)?> member(s) shown.</p></div></div><div class="table-responsive"><table class="table table-clean align-middle"><thead><tr><th>Member</th><th>Membership No.</th><th>Contact</th><th>Status</th><th>Last login</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=e($r['full_name'])?></strong></td><td><?=e($r['membership_no'])?></td><td><?=e($r['phone'])?><br><small><?=e($r['email'])?></small></td><td><span class="badge text-bg-<?=$r['status']==='active'?'success':'secondary'?>"><?=e(ucfirst($r['status']))?></span></td><td><?=e($r['last_login_at']?date('d M Y, g:i A',strtotime($r['last_login_at'])):'Never')?></td><td class="text-end"><div class="d-flex justify-content-end gap-1 flex-wrap"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle_status"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-outline-<?=$r['status']==='active'?'danger':'success'?>" onclick="return confirm('Change this member account status?')"><?= $r['status']==='active'?'Deactivate':'Activate' ?></button></form><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="reset_password"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-outline-primary" onclick="return confirm('Reset this member password and activate the account?')"><i class="bi bi-key me-1"></i>Reset password</button></form></div></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="6" class="empty">No members match your search.</td></tr><?php endif;?></tbody></table></div></div></div></main></div>
<?php require __DIR__.'/../includes/footer.php';?>
